CREATE TABLE IF NOT EXISTS notificaciones (
    id        SERIAL      PRIMARY KEY,
    grupo     TEXT        NOT NULL DEFAULT 'mesas'
                          CHECK (grupo IN ('mesas', 'social', 'sesiones')),
    icono     TEXT        NOT NULL DEFAULT 'solicitud',
    leida     BOOLEAN     NOT NULL DEFAULT FALSE,
    autor     TEXT,
    mensaje   TEXT        NOT NULL,
    entidad   TEXT,
    detalle   TEXT,
    enlace    JSONB,
    fecha     TEXT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS event_log (
    id           SERIAL      PRIMARY KEY,
    entidad_tipo TEXT        NOT NULL,
    entidad_id   TEXT,
    accion       TEXT        NOT NULL,
    usuario_id   TEXT,
    metadata     JSONB,
    ocurrido_en  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_event_log_entidad ON event_log (entidad_tipo, entidad_id);

-- B05: trazabilidad de eventos asincronos (RabbitMQ). Aditivo/idempotente.
ALTER TABLE notificaciones ADD COLUMN IF NOT EXISTS usuario_id BIGINT;
ALTER TABLE event_log ADD COLUMN IF NOT EXISTS event_id VARCHAR(64);
CREATE UNIQUE INDEX IF NOT EXISTS idx_event_log_event_id
    ON event_log (event_id) WHERE event_id IS NOT NULL;

-- F09: trazabilidad por correlation_id en el event-log (B10 punta a punta).
ALTER TABLE event_log ADD COLUMN IF NOT EXISTS correlation_id VARCHAR(64);
CREATE INDEX IF NOT EXISTS idx_event_log_correlation
    ON event_log (correlation_id) WHERE correlation_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS mensaje_dlq (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cola    VARCHAR(64) NOT NULL,
    payload TEXT NOT NULL,
    error   TEXT NOT NULL,
    fecha   TIMESTAMPTZ DEFAULT now()
);

-- B08: documentos generados de forma asincrona (PDF de comprobante).
-- id es el documento_id que el emisor (builds-api) devuelve en el 202.
CREATE TABLE IF NOT EXISTS documentos (
    id        VARCHAR(36) PRIMARY KEY,
    tipo      VARCHAR(16) NOT NULL CHECK (tipo IN ('build', 'diario')),
    id_origen BIGINT NOT NULL,
    ruta      TEXT,
    estado    VARCHAR(16) NOT NULL DEFAULT 'en_proceso'
                           CHECK (estado IN ('en_proceso', 'listo', 'error')),
    fecha     TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_documentos_origen ON documentos (tipo, id_origen);

-- B09: outbox de emails (proveedor SMTP sandbox MailHog). Aditivo/idempotente.
CREATE TABLE IF NOT EXISTS emails (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destino VARCHAR(255) NOT NULL,
    asunto  VARCHAR(200) NOT NULL,
    cuerpo  TEXT NOT NULL,
    estado  VARCHAR(16) NOT NULL DEFAULT 'enviado'
            CHECK (estado IN ('enviado', 'fallido')),
    error   TEXT,
    fecha   TIMESTAMPTZ DEFAULT now()
);