CREATE TABLE IF NOT EXISTS mesas (
    id             SERIAL      PRIMARY KEY,
    nombre         TEXT        NOT NULL,
    sistema        TEXT        NOT NULL,
    descripcion    TEXT,
    tono           TEXT,
    horario        TEXT,
    estado         TEXT        NOT NULL DEFAULT 'abierta'
                               CHECK (estado IN ('abierta', 'cerrada')),
    nivel_inicial  INTEGER,
    jugadores_max  INTEGER,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mesas_estado ON mesas (estado);

CREATE TABLE IF NOT EXISTS usuarios (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(255) NOT NULL UNIQUE,
    password_hash  TEXT    NOT NULL,
    rol            VARCHAR(16) NOT NULL DEFAULT 'usuario'
                   CHECK (rol IN ('usuario', 'gm', 'admin')),
    nombre         VARCHAR(120) NOT NULL,
    fecha_creacion TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS matchmaking (
    id                SERIAL      PRIMARY KEY,
    mesa_id           INTEGER     NOT NULL REFERENCES mesas (id) ON DELETE CASCADE,
    estado            TEXT        NOT NULL DEFAULT 'llamada_abierta'
                                  CHECK (estado IN ('llamada_abierta', 'cerrada', 'completa')),
    llamada_abierta_at TIMESTAMPTZ,
    fecha_creacion    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_matchmaking_mesa ON matchmaking (mesa_id);

-- B06: conteo de ocupación y registro de solicitudes (carrera por la última vacante).
ALTER TABLE mesas ADD COLUMN IF NOT EXISTS jugadores_actuales INT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS solicitudes_uniones (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mesa_id    INTEGER     NOT NULL REFERENCES mesas (id) ON DELETE CASCADE,
    usuario_id BIGINT      NOT NULL,
    estado     TEXT        NOT NULL DEFAULT 'pendiente'
                           CHECK (estado IN ('pendiente', 'aceptada', 'rechazada')),
    idem_key   VARCHAR(64),
    fecha      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_solicitudes_mesa_usuario ON solicitudes_uniones (mesa_id, usuario_id);