CREATE TABLE IF NOT EXISTS mesas (
    id             SERIAL      PRIMARY KEY,
    nombre         TEXT        NOT NULL,
    sistema        TEXT        NOT NULL,
    descripcion    TEXT,
    tono           TEXT,
    horario        TEXT,
    estado         TEXT        NOT NULL DEFAULT 'abierta'
                               CHECK (estado IN ('abierta', 'cerrada')),
    nivel_inicial  INTEGER,
    jugadores_max  INTEGER,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mesas_estado ON mesas (estado);

CREATE TABLE IF NOT EXISTS usuarios (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(255) NOT NULL UNIQUE,
    password_hash  TEXT    NOT NULL,
    rol            VARCHAR(16) NOT NULL DEFAULT 'usuario'
                   CHECK (rol IN ('usuario', 'gm', 'admin')),
    nombre         VARCHAR(120) NOT NULL,
    fecha_creacion TIMESTAMPTZ DEFAULT now()
);